### ISSUE TITLE
WritePoints very slow

### ISSUE THREAD

**Issue by benberlin7** [MalikRizwanBashir/QuestDB.Net#1]
Hey.
I have followed the steps in your quickstart introduction. I'm trying to transfer 129600 points to the database.

I tried two different approachs : 
#1 writePoint for every point
#2 gather list of points and writePoints at the end one time

#1
`//One Point for every minute
                          
                            for (int min_idx = 0; min_idx < values.Length; min_idx++)
                            {
                                timestamp = Convert.ToInt32(double_vals[0, min_idx]);
                                var point = Questdb.Net.Write.PointData.Measurement(measurement)
                                .Tag("seconds_passed", timestamp.ToString())
                                .Timestamp(Convert.ToInt64(timestamp), Questdb.Net.Write.WritePrecision.Seconds);

                                for (int col_idx = 0; col_idx < headers.Length - 1; col_idx++)
                                {
                                    point.Field(headers[col_idx], double_vals[col_idx, min_idx]);
                                }
                                writeApi.WritePoint(point);
                            }
`

#2
                           
```
                            List<Questdb.Net.Write.PointData> list_of_points = new List<Questdb.Net.Write.PointData>();
                          
                            for (int min_idx = 0; min_idx < values.Length; min_idx++)
                            {
                                timestamp = Convert.ToInt32(double_vals[0, min_idx]);
                                var point = Questdb.Net.Write.PointData.Measurement(measurement)
                                    .Tag("seconds_passed", timestamp.ToString())
                                    .Timestamp(Convert.ToInt64(timestamp), Questdb.Net.Write.WritePrecision.Seconds);

                                for (int col_idx = 0; col_idx < headers.Length - 1; col_idx++)
                                {
                                    point.Field(headers[col_idx], double_vals[col_idx, min_idx]);
                                }
                            list_of_points.Add(point);
                            }
                            writeApi.WritePoints(list_of_points);
```

Both approaches take incredibly long. The first approach gets ~8500 points per minute and the second took 17,5 minutes to write all points. 

What am I doing wrong?

**Comment by MalikRizwanBashir** [comment]
@benberlin7 Please try with the latest version. Performance is improved.
I tested, it took 2.8 sec with bulk insertion for 500,000 points having 9 fields and took 10 sec with insertion in loop.

**Comment by MalikRizwanBashir** [comment]
Considering issue is resolved.
