### ISSUE TITLE
Hidden Exception

### ISSUE THREAD

**Issue by null-ref-ex** [MalikRizwanBashir/QuestDB.Net#2]
https://github.com/MalikRizwanBashir/QuestDB.Net/blob/70c17018820c119dd888c2fabb06e21d354d5416/Questdb.Net/Write/LineProtocol/TcpService.cs#L30

When supplying the host as an IP such as `http://1.2.3.4/` the WriteApi silently fails. This referenced method above is throwing an exception. Ideally you should `IPAddress.TryParse` to figure out if the provided address is already an IP or not and only do the DNS lookup as needed.

**Comment by rizwanbashirstackone** [comment]
@null-ref-ex Now exception will be thrown if host is invalid while creating connection.
Please check with latest package. IPAddress.TryParse doesn't work in this case.

**Comment by null-ref-ex** [comment]
Is providing `http://1.2.3.4` considered to be an invalid target host? Documented usage examples show using an IP and it seems like a valid use case... not all destinations are going to be DNS resolvable. `IPAddress.TryParse` will work in enabling you to determine if the user provided an IP address rather than a host name.

**Comment by MalikRizwanBashir** [comment]
Issue is fixed in 1.3.0 release.
